//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinFormsApp1 {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinFormsApp1.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 C:\Program Files (x86)\Google\Chrome\Application\chrome.exe 的當地語系化字串。
        /// </summary>
        public static string browserPath {
            get {
                return ResourceManager.GetString("browserPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 img\ 的當地語系化字串。
        /// </summary>
        public static string dirPath {
            get {
                return ResourceManager.GetString("dirPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 甲烷是一種短暫但強效的溫室氣體，是全球第二大溫室效應來源，僅次於二氧化碳。UNEP報告指出，大氣中甲烷濃度現處於有記錄的40年來最高水準，人為排放主要來自畜牧業、化石燃料生產和廢棄物產業。
        ///
        ///報告也提出了快速減少甲烷排放的方法，針對農牧、化石燃料生產和廢棄物產業推出一系列的措施，10年後甲烷排放量可減少45％。研究估計，如此一來有機會使全球在2045年降溫0.3°C，要達到巴黎協定本世紀末升溫1.5°C內的目標，這樣的降溫方式有其必要。 的當地語系化字串。
        /// </summary>
        public static string info_ch4 {
            get {
                return ResourceManager.GetString("info_ch4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 截至2019年5月，地球大氣層中的二氧化碳濃度曾一度超過415 ppm（百萬分之415或0.0415%）。2000至2009年間的濃度增長率為每年2.0 ppm，且逐年加速。目前的濃度比工業化之前的280 ppm濃度高得多，而人為因素是導致二氧化碳濃度急劇上升的主要原因。釋放出的二氧化碳中，57%進入大氣層，其餘的則進入海洋，造成海洋酸化。
        ///
        ///多達四成的地面二氧化碳排放是由於火山爆發。據估計，每年火山爆發釋放約130-230萬公噸（145-255萬噸）二氧化碳到大氣中。溫泉等也產生大量二氧化碳。人類排放的二氧化碳超過火山爆發排放量130倍以上：2018年全球排放量為365.7億公噸。 的當地語系化字串。
        /// </summary>
        public static string info_co2 {
            get {
                return ResourceManager.GetString("info_co2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 從1880年到2017年全球表面平均溫度值，相對於1951年-1980年的14.19°C平均值而言。黑線是全球年均值，紅線是5年局部回歸線。藍色的不確定條顯示了95%的置信區間。 的當地語系化字串。
        /// </summary>
        public static string info_globalTemp {
            get {
                return ResourceManager.GetString("info_globalTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 這裡還沒有參考資料。 的當地語系化字串。
        /// </summary>
        public static string info_nothing {
            get {
                return ResourceManager.GetString("info_nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 https://www.bbc.com/zhongwen/trad/science-57749347 的當地語系化字串。
        /// </summary>
        public static string Resource_1 {
            get {
                return ResourceManager.GetString("Resource_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 https://tomorrowsci.com/environment/%E4%BA%BA%E9%A1%9E%E6%B4%BB%E5%8B%95%E5%BD%B1%E9%9F%BF%E5%A4%A7%E6%B0%A3%E7%B5%90%E6%A7%8B%EF%BC%8C%E5%9C%B0%E7%90%83%E7%9A%84%E5%B0%8D%E6%B5%81%E5%B1%A4%E6%AD%A3%E4%B8%8D%E6%96%B7%E5%9C%B0%E6%93%B4/ 的當地語系化字串。
        /// </summary>
        public static string Resource_2 {
            get {
                return ResourceManager.GetString("Resource_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 https://blog.xuite.net/wild.fun/blog/589591068 的當地語系化字串。
        /// </summary>
        public static string Resource_3 {
            get {
                return ResourceManager.GetString("Resource_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 氣候變化是今日國際頭等大事之一，全球變暖帶來的各種變化日漸顯著。聯合國提出一個地球變暖的上限 — 氣溫比前工業化時代最多高1.5℃，科學家指出，要達到這個目標，前提是社會生活各個層面發生迅疾的、影響長遠的、前所未見的改變。 的當地語系化字串。
        /// </summary>
        public static string text_2000 {
            get {
                return ResourceManager.GetString("text_2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 氣候變暖跟溫室效應有關 — 太陽光照到地球表面，再反射回天空，被大氣層裏的二氧化碳（溫室氣體）吸收，然後向各處釋放。這個自然發生的過程中，靠近地面的大氣層和地球表面溫度會升高。如果沒有溫室效應，地球上會天寒地凍，不適宜生命體生存。 的當地語系化字串。
        /// </summary>
        public static string text_2002 {
            get {
                return ResourceManager.GetString("text_2002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 2006年6月7日在挪威觀測到一顆隕石掉落在特羅姆斯郡挪德麗莎的瑞瑟達倫（Reisadalen）。雖然目擊者一開始報告該次撞擊造成的火球相當於廣島市原子彈爆炸能量；但科學家分析撞擊地點後認為爆炸能量相當於100到500公噸TNT爆炸當量，相當於小男孩原子彈能量的3% [21] 的當地語系化字串。
        /// </summary>
        public static string text_2006 {
            get {
                return ResourceManager.GetString("text_2006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 2007年9月15日，一顆球粒隕石墜落在秘魯西南靠近的的喀喀湖的卡藍卡斯附近村莊（卡藍卡斯撞擊事件）。該隕石落在一個充滿水的坑中，並在鄰近區域散發大量氣體。許多當地居民吸入氣體後感覺身體不適，應是撞擊後散短時間內散發有毒氣體。 的當地語系化字串。
        /// </summary>
        public static string text_2007 {
            get {
                return ResourceManager.GetString("text_2007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 2009年11月21日有一個火球被南非的警用和交通攝影機拍攝下來。這個可能是流星的物體被認為落在南非和波札那邊界一帶的偏遠地區，並可能產生了一次小規模撞擊 的當地語系化字串。
        /// </summary>
        public static string text_2009 {
            get {
                return ResourceManager.GetString("text_2009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 二氧化碳、甲烷、一氧化二氮等都屬於溫室氣體，但在氣候變化中起作用最大的是二氧化碳CO2。
        ///水蒸氣形態的溫室氣體升溫作用最明顯，但這種氣體在大氣層裏只會停留幾天，而滯留時間較長的是二氧化碳。
        ///1750年工業革命開始以來，大氣層裏的二氧化碳增加了30%，CO2濃度有史以來最高。
        ///如果要把大氣層裏的二氧化碳含量降到工業化之前的水平，大致需要數百年。海洋可以吸收二氧化碳，但能力有限。
        ///人類活動產生的二氧化碳主要來自化石燃料的燃燒。此外，開荒伐木也會增加碳排放、加劇全球變暖。 的當地語系化字串。
        /// </summary>
        public static string text_2013 {
            get {
                return ResourceManager.GetString("text_2013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 幾十年來，學術界認為在本世界末之前應該把地球升溫幅度控制在比工業化前平均值高2℃的程度才算「安全」，才能避免「最壞情況」發生。
        ///
        ///在現實中，如果把《巴黎氣候協議》簽約國各自承諾的碳減排總和計算在內，到本世紀末地球氣溫將升高至少3℃，世界氣象組織的預測是升高3-5℃。
        ///
        ///現在世界公認的「安全」程度是比工業化前平均值高1.5℃。 的當地語系化字串。
        /// </summary>
        public static string text_2018 {
            get {
                return ResourceManager.GetString("text_2018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 這裡還沒有事件內容。 的當地語系化字串。
        /// </summary>
        public static string text_nothing {
            get {
                return ResourceManager.GetString("text_nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 　　　　　　　　　　　　　　　　　　　　　　   　　　開始拖動滑桿來感受地球大氣層隨著年代的變化吧。　　　　　　　　　　　　　　　　　　　　　　　　　　　　　　點擊圖表有更多詳細資訊。 的當地語系化字串。
        /// </summary>
        public static string text_roll {
            get {
                return ResourceManager.GetString("text_roll", resourceCulture);
            }
        }
    }
}
